// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// This module is the single source of truth for PDFX styling tokens.
// Update the exported `theme` object to customize component styles.

interface PdfxTheme {
  name: string;
  primitives: {
    typography: Record<string, number>;
    spacing: Record<string | number, number>;
    fontWeights: { regular: number; medium: number; semibold: number; bold: number };
    lineHeights: { tight: number; normal: number; relaxed: number };
    borderRadius: { none: number; sm: number; md: number; lg: number; full: number };
    letterSpacing: { tight: number; normal: number; wide: number; wider: number };
  };
  colors: {
    foreground: string;
    background: string;
    muted: string;
    mutedForeground: string;
    primary: string;
    primaryForeground: string;
    border: string;
    accent: string;
    destructive: string;
    success: string;
    warning: string;
    info: string;
  };
  typography: {
    body: { fontFamily: string; fontSize: number; lineHeight: number };
    heading: {
      fontFamily: string;
      fontWeight: number;
      lineHeight: number;
      fontSize: { h1: number; h2: number; h3: number; h4: number; h5: number; h6: number };
    };
  };
  spacing: {
    page: { marginTop: number; marginRight: number; marginBottom: number; marginLeft: number };
    sectionGap: number;
    paragraphGap: number;
    componentGap: number;
  };
  page: {
    size: 'A4' | 'LETTER' | 'LEGAL';
    orientation: 'portrait' | 'landscape';
  };
}

export const theme: PdfxTheme = {
  name: "professional",

  // Primitive scales.
  primitives: {
    typography: {
      xs: 7,
      sm: 8,
      base: 10,
      lg: 12,
      xl: 14,
      '2xl': 18,
      '3xl': 24,
    },
    spacing: {
      0: 0,
      0.5: 1,
      1: 2,
      2: 4,
      3: 6,
      4: 8,
      5: 10,
      6: 12,
      8: 16,
      10: 20,
      12: 24,
      16: 32,
    },
    fontWeights: {
      regular: 400,
      medium: 700,
      semibold: 700,
      bold: 700,
    },
    lineHeights: {
      tight: 1.2,
      normal: 1.4,
      relaxed: 1.6,
    },
    borderRadius: {
      none: 0,
      sm: 0,
      md: 0,
      lg: 0,
      full: 0,
    },
    letterSpacing: {
      tight: -0.025,
      normal: 0,
      wide: 0.025,
      wider: 0.05,
    },
  },

  // Semantic colors. Values must be valid for react-pdf.
  colors: {
    foreground: "#000000",
    background: "#ffffff",
    muted: "transparent",
    mutedForeground: "#000000",
    primary: "transparent",
    primaryForeground: "#000000",
    border: "#000000",
    accent: "#000000",
    destructive: "#000000",
    success: "#000000",
    warning: "#000000",
    info: "#000000",
  },

  // Typography defaults.
  typography: {
    body: {
      fontFamily: "Helvetica",
      fontSize: 7,
      lineHeight: 1.2,
    },
    heading: {
      fontFamily: "Helvetica-Bold",
      fontWeight: 700,
      lineHeight: 1.25,
      fontSize: {
        h1: 24,
        h2: 18,
        h3: 14,
        h4: 12,
        h5: 10,
        h6: 8,
      },
    },
  },

  // Layout spacing.
  spacing: {
    page: {
      marginTop: 20,
      marginRight: 20,
      marginBottom: 20,
      marginLeft: 20,
    },
    sectionGap: 3,
    paragraphGap: 3,
    componentGap: 0,
  },

  // Page defaults.
  page: {
    size: "A4",
    orientation: "portrait",
  },
};
